- Gemfile.lock
- app/models/concerns/can_deactivate_exemption.rb
- app/models/waste_exemptions_engine/registration.rb
- app/presenters/confirmation_letter_presenter.rb
- db/schema.rb
- lib/defra_ruby/exporters/registration_bulk_export_report.rb
- spec/factories/registration_exemption.rb
- spec/models/registration_exemption_spec.rb
- spec/models/registration_spec.rb
- spec/services/deregistration_service_spec.rb
This is just about keeping things consistent. Where we are recording a timestamp the pattern has been to use `name_of_field_at` rather than `name_of_field_on`.
For example `created_at`, `updated_at`, and `submitted_at`. This change is just about keeping things consistent.
For reference the rename migration is stored in the [waste-exemptions-engine](https://github.com/defra/waste-exemptions-engine) however all functionality related to deregistering is here hence this change.
> Rename deregistered_on to deregistered_at

- spec/models/registration_spec.rb
It's late. We're into the first dark minutes of a fresh new day but my body is haggard from the last. The screen before me is starting to blur and my bones are pleading for respite and the embrace of sleep, but I push on.
One last push. Only one more, then I'm done.
Muted orange circles, the wheel spins and then the gatekeeper awakens. Arcane letters spill out in jumps and starts but its the dots, the little green dots.
We expect them too, assume they will appear, one hand resting on the lid and our soul two steps already to bed.
...........F......
NO!!!!! How can this be. Our efforts were small and inconsequential. They did little, yet they are rejected. It's broken. YOU have broken something. You are not done.
---
I have spotted a test that can be made to fail if run at a specific time, …
> Fix test fail when run at midnight BST

- Gemfile
- Gemfile.lock
- config/initializers/wicked_pdf.rb
- script/wkhtmltopdf.sh
part of: https://eaflood.atlassian.net/browse/RUBY-223
The wicked_pdf gem, initializer config and script are already part of the engine code and dependency of this application.
Requiring and installing the gem twice was causing an error generation in the PDF recorded in the ticket above, for which a PDF was generated with wrong content.
> Remove wickedpdf gem and configs

- config/initializers/defra_ruby_exporters.rb
https://eaflood.atlassian.net/browse/RUBY-380
Looks like the reported issue has to deal with the fact that the override classes files were not required in the initializer.
The dummy data created by testing it on the server were generating records for the entire year due to https://github.com/DEFRA/defra-ruby-exporters/blob/master/lib/defra_ruby/exporters/registration_bulk_export_report.rb#L16.
This fixes the issue. Steps forward are for DEV to come together and discuss what to do with this gem.
Eventually, we want an error to be raised if the application using the gem is missing such important files that belongs to the app itself.
Also, this gem is not an engine, and using the strategy of opening the class and re-write the method for it to work doesn't look the best option for me.
> Fix WEX data exports

- app/views/shared/_resource_address.html.erb
- config/locales/partials/resource_address.en.yml
- db/schema.rb
https://eaflood.atlassian.net/browse/RUBY-25
The existing service has the ability to lookup the EA admin area for a site using the easting and northing values. This is currently out of action whilst we await a fix (the external service we call changed supplier and we have been awaiting support for what the new query should be).
However it has been spotted in our work on migrating the old data to the new schema that we don't have a field for this. So on the basis we want to retain this data, and that we expect to implement the lookup feature in the new service once the issue is resolved, this change adds update the WEX engine to bring in a version that adds `area` to the **address** and **transient_address** models.
It will also update the registration details view to include this …
> Update to include site address area

- Gemfile
- Gemfile.lock
- app/services/reports/monthly_bulk_report_service.rb
- config/application.rb
- config/initializers/defra_ruby_aws.rb
- spec/factories/registration_exemption.rb
- spec/services/reports/monthly_bulk_report_service_spec.rb
Part of: https://eaflood.atlassian.net/browse/RUBY-392
Implements loading the Bulk report files to Aws bucket using the `defra-ruby-aws` gem.
This also adds end-to-end test coverage. Next step is to implement the records update. 
This is also dependent from: https://github.com/DEFRA/defra-ruby-exporters/pull/9 and https://github.com/DEFRA/defra-ruby-aws/pull/4
> Implement Aws bucket load of report bulk CSV files

- lib/tasks/reports.rake
https://eaflood.atlassian.net/browse/RUBY-392
Within the codebase we have amended the namespace for our exports to be `reports`. However we didn't make the same change to the rake task namespace used to actually generate them.
This change makes that change.
> Update reports namespace to be consistent

- app/controllers/bulk_exports_controller.rb
- app/models/ability.rb
- app/models/reports/generated_report.rb
- app/views/layouts/application.html.erb
- spec/support/shared_examples/abilities/data_agent_examples.rb
From https://eaflood.atlassian.net/browse/RUBY-392
Stop using the old exporters model and instead use the new Reports::GeneratedReport model when dealing with ability permissions
> Use the new Reports::GeneratedReport to deal with reports permissions

- app/presenters/reports/exemption_bulk_report_presenter.rb
- spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
https://eaflood.atlassian.net/browse/RUBY-392
Return a nil value for the site address export details when the site is located by a grid reference.
> Return blank site address when location is by grid reference

- .travis.yml
Following Trravis build failures we have noticed that the travis VM have updated the Postgres version from 9.6 to 10+ when the errrors started appearing.
This downgrade fixes the situation for now.
I am not 100% sure about the real issue, since the current PG gem version is suppose to support postgres 10+.
A ticket have been created to follow up on this:
https://github.com/DEFRA/ruby-services-team/issues/30
> Downgrade Postgres version to 9.6

- .travis.yml
- app/presenters/reports/exemption_bulk_report_presenter.rb
- spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Part of: https://eaflood.atlassian.net/browse/RUBY-392 
I was under the impression that since the `assistance_mode` was a string type field with no obvious constraint it would contain just the same string as the CSV. Instead seems like we populate the field to `full` when the registration is a fully assisted one while we leave it blank otherwise.
Fix the code so that we will return the string "fully assisted" when the field is set to "full" and "unassisted" otherwise.
Depends on: https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/218
> Change return field for assisted mode

- .travis.yml
- app/presenters/reports/exemption_bulk_report_presenter.rb
- spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Part of: https://eaflood.atlassian.net/browse/RUBY-392 
In order to keep consistent with the old bulk export, we are removing the operator field from the addresses in the bulk export data.
Depends on: https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/218
>  Remove operator from address data bulk export

- Gemfile
- Gemfile.lock
We renamed this to use snake case instead of kebab case.
Resolves https://github.com/DEFRA/waste-exemptions-back-office-ta/issues/232
> Fix defra_ruby_aws gem name

- app/helpers/dashboards_helper.rb
- config/locales/partials/search_result.en.yml
- spec/helpers/dashboards_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-432
Use the registration state on the dashboard in order for a user to have a visual information about the registration status.
> Use registration state when displaying registrations in the dashboard

- app/mailers/renewal_reminder_mailer.rb
- app/views/renewal_reminder_mailer/first_reminder_email.html.erb
- app/views/renewal_reminder_mailer/first_reminder_email.txt.erb
- config/locales/mailers/renewal_reminder_email.en.yml
- lib/tasks/one_off/reminders.rake
- spec/factories/address.rb
- spec/factories/registration.rb
- spec/mailers/renewal_mailer_spec.rb
- spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
https://eaflood.atlassian.net/browse/RUBY-252
This is the first reminder email that digital users will get. It should be sent 4 weeks before the registration is due to expire.
This story covers building the mailer and putting the HTML and text into the code.
You can test this with the last registration in the database by running `bundle exec rake reminder:first`. (We'll rip this out once we have something actually triggering it, but for now this is there for testing.)
> Build first reminder email

- app/views/deregister_exemptions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_resource_address.html.erb
- app/views/shared/_resource_details.html.erb
From https://eaflood.atlassian.net/browse/RUBY-388
Fixes HTML issues from W3C validation
It does not include test coverage which is currently blocked due to an issue with cancancan abilities in the test suite
Issue fixed were about: 
- Misplaced / duplicated tag ids 
- Space in the `mailto` link 
- label `for` attribute pointing to non-existing objects 
- `aria-controls` tag pointing to the wrong object
> Fix HTML W3C issues

- .env.example
- config/schedule.rb
- spec/schedule_spec.rb
Now we have completed the migrations work, we have been able to run the bulk export in pre-production with production volumes. It currently takes 23 minutes, and we believe that is perfectly acceptable as a daily rather than weekly job.
Hence this change which removes the frequency element of the bulk export schedule, setting it to run daily at 20:05.
> Update bulk exporter schedule to be daily

- config/schedule.rb
- lib/tasks/email.rake
- spec/schedule_spec.rb
This renames the Email reminders to include `first` so that we can distinguish between the first and second email reminders later on.
Open to suggestion. I am not super super happy about this naming 🤔
> Rename email reminders task to include `first`

- app/views/shared/_resource_details.html.erb
From https://eaflood.atlassian.net/browse/RUBY-383
This was missing the `mailto:` entirely while the other one fixed had an empty space.
> Add missing mailto to link

- app/services/reports/bulk_export_service.rb
When the current date is the first day of the month, we expect the report service to generate a document for the current month as well.
This wasn't the case, and the test suite issue happening on the first day of the month sparked light on the bug.
> Fix bug on first day of the month bulk report generation

- app/presenters/confirmation_letter_presenter.rb
- config/locales/confirmation_letters.en.yml
- spec/presenters/confirmation_letter_presenter_spec.rb
https://eaflood.atlassian.net/browse/RUBY-453
Prior to this change if the registration contained an exemption with a state of `expired` it would error when the user attempted to view the confirmation letter.
A quick check of the code identified that the logic in the `ConfirmationLetterPresenter.registration_exemption_status()` method would attempt to generate a display version of the deregistered date for any exemption without a status of `active`.
The problem is that an expired exemption does not have a deregistered date hence the code was failing. So a quick tweak of the logic and 🎉 we have a working confirmation letter.
> Fix error when in confirmation letter for expired

- spec/factories/new_registration.rb
- spec/factories/registration.rb
- spec/models/registration_exemption_spec.rb
- spec/models/reports/monthly_bulk_serializer_spec.rb
- spec/rails_helper.rb
This removes the need of seeding Exemption in the database and fixes connected specs.
Housekeeping and alignment with other services.
> Do not seed exemptions in the test suite, use factories instead

- app/views/renewal_reminder_mailer/first_reminder_email.html.erb
https://eaflood.atlassian.net/browse/RUBY-252
This change removes an extra border appearing in some versions of Outlook, and removes an unwanted space in a mailto link.
> Fix minor bugs in first email reminder

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
From https://eaflood.atlassian.net/browse/RUBY-117
Includes polyfill file and javascript application and init the polyfill details JS class
> Include polyfill for old browsers support

- app/helpers/mailer_helper.rb
- app/mailers/renewal_reminder_mailer.rb
- app/views/renewal_reminder_mailer/first_reminder_email.html.erb
- spec/mailers/renewal_mailer_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-252
Attach logo to email as per WCR instead of linking to Gov.uk
>  Attach logo to email instead of linking to gov.uk 

- app/views/pages/privacy.html.erb
For whatever reason, the version of the privacy policy in the back office has not been updated inline with the version in the front office. So prior to this change it was still the old version prior to our GDPR review.
It's possibly the fact the link to the privacy policy in the footer does not exist in the back office, and hence it was overlooked. However with the new verbal privacy policy we do have a link, but without this change users will see the old content.
This change updates it to bring it inline with the front office, with GDPR reviewed content.
> Update privacy policy

- Gemfile
- Gemfile.lock
- app/helpers/action_links_helper.rb
- app/views/new_registrations/show.html.erb
- config/locales/new_registrations.en.yml
- config/routes.rb
- spec/factories/new_registration.rb
- spec/helpers/action_links_helper_spec.rb
- spec/presenters/reports/exemption_epr_report_presenter_spec.rb
- spec/requests/new_registrations_spec.rb
- spec/services/search_service_spec.rb
Since in progress registrations will not have any more a reference number, we will have to use the ID instead. Hence this updates the rules of the route and removes the reference number from the heading of the show view.
> Use id instead of reference when dealing with in progress registrations

- app/controllers/new_registrations_controller.rb
Since we updated the routes to pass through the Id instead of the reference, we also need to update the controller to use the correct parameter to fetch the resource
> Use id instead of reference to find the correct new registration
